### ISSUE TITLE
adhere to NLeSC software checklist

### ISSUE THREAD

**Issue by bakhshir** [indodutch/sim-city-stack#23]
Version control

- [x] version control from the beginning of the project
- [x] use git as version control system (vcs)
- [x] choose one branching model
- [x] public vcs repository
- [ ] meaningful commit messages **need to work on this**

Releases

- [x] semantic versioning
- [x] tagged releases
- [x] CHANGELOG.md
- [x] one command install
- [ ] package in package manager
- [x]  discuss release cycle with coordinator
- [x] release quick-scan by other engineer
- [ ] Citeable
- [ ] Dissemination

Licensing

- [x] Apache 2 license
- [ ] compatible license of all libraries
- [ ] NOTICE(.txt|.md)

Communication

- [ ] home page
- [ ] discussion list
- [ ] demo docker image in dockerhub (with Dockerfile)
- [ ] an online demo
- [ ] screencast

Code Quality

- [x] use editorconfig
- [ ] code style applied in automated way

Testing

- [ ] unit tests
- [ ] continuous integration
- [ ] continuous code coverage
- [ ] end2end test
- [ ] dependencies tracking

Documentation

- [ ] README.md
- [ ] well defined functionality
- [ ] source code documentation
- [ ] usage documentation
- [ ] documented development setup
- [x] contribution guidelines
- [ ] code of conduct
- [ ] documented code style
- [ ] how to file a bug report
- [ ] explained meaning of issue labels
- [ ] DOI or PID
- [ ] CITATION file
- [ ] print software version

Development setup

- [ ] dev environment docker images in Dockerhub (with Dockerfile)

Standards

- [ ] Exchange formats
- [ ] Protocols

NOTE: we can check master branch of TNO CS repo for missing components of our repo
see https://github.com/TNOCS/csWeb/

More comment in [checklist.txt](https://github.com/ReGIS-org/regis-stack/files/1320746/checklist.txt)
